# Generated by Django 2.2.3 on 2020-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default='Vev5UA', max_length=6, primary_key=True, serialize=False),
        ),
    ]
