# Generated by Django 2.2.3 on 2020-01-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200120_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='pRixlG', max_length=7, unique=True),
        ),
    ]
