# Generated by Django 2.2.3 on 2020-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200120_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='#anZFUtJ', max_length=20, unique=True),
        ),
    ]
