# Generated by Django 3.0.2 on 2020-02-02 13:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='message'),
        ),
    ]
