# Generated by Django 3.0.2 on 2020-02-03 05:34

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200202_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, max_length=10, null=True, upload_to=chat.models.user_files),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
